/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as OValenRouteImport } from './routes/o-valen'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExperienciasRouteImport } from './routes/experiencias'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConecteSeRouteImport } from './routes/conecte-se'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicosTruckCenterRouteImport } from './routes/servicos.truck-center'
import { Route as ServicosPostoRouteImport } from './routes/servicos.posto'
import { Route as ServicosHotelRouteImport } from './routes/servicos.hotel'
import { Route as ServicosClubeDoCaminhoneiroRouteImport } from './routes/servicos.clube-do-caminhoneiro'
import { Route as ServicosAlimentacaoRouteImport } from './routes/servicos.alimentacao'
import { Route as PromocoesSlugRouteImport } from './routes/promocoes.$slug'
import { Route as LojasSlugRouteImport } from './routes/lojas.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminPromocoesIndexRouteImport } from './routes/admin.promocoes.index'
import { Route as AdminLojasIndexRouteImport } from './routes/admin.lojas.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminPromocoesNovoRouteImport } from './routes/admin.promocoes.novo'
import { Route as AdminPromocoesIdRouteImport } from './routes/admin.promocoes.$id'
import { Route as AdminLojasNovoRouteImport } from './routes/admin.lojas.novo'
import { Route as AdminLojasIdRouteImport } from './routes/admin.lojas.$id'
import { Route as AdminBlogNovoRouteImport } from './routes/admin.blog.novo'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OValenRoute = OValenRouteImport.update({
  id: '/o-valen',
  path: '/o-valen',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciasRoute = ExperienciasRouteImport.update({
  id: '/experiencias',
  path: '/experiencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConecteSeRoute = ConecteSeRouteImport.update({
  id: '/conecte-se',
  path: '/conecte-se',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicosTruckCenterRoute = ServicosTruckCenterRouteImport.update({
  id: '/servicos/truck-center',
  path: '/servicos/truck-center',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPostoRoute = ServicosPostoRouteImport.update({
  id: '/servicos/posto',
  path: '/servicos/posto',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosHotelRoute = ServicosHotelRouteImport.update({
  id: '/servicos/hotel',
  path: '/servicos/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosClubeDoCaminhoneiroRoute =
  ServicosClubeDoCaminhoneiroRouteImport.update({
    id: '/servicos/clube-do-caminhoneiro',
    path: '/servicos/clube-do-caminhoneiro',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosAlimentacaoRoute = ServicosAlimentacaoRouteImport.update({
  id: '/servicos/alimentacao',
  path: '/servicos/alimentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesSlugRoute = PromocoesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PromocoesRoute,
} as any)
const LojasSlugRoute = LojasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LojasRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminPromocoesIndexRoute = AdminPromocoesIndexRouteImport.update({
  id: '/promocoes/',
  path: '/promocoes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasIndexRoute = AdminLojasIndexRouteImport.update({
  id: '/lojas/',
  path: '/lojas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromocoesNovoRoute = AdminPromocoesNovoRouteImport.update({
  id: '/promocoes/novo',
  path: '/promocoes/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromocoesIdRoute = AdminPromocoesIdRouteImport.update({
  id: '/promocoes/$id',
  path: '/promocoes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasNovoRoute = AdminLojasNovoRouteImport.update({
  id: '/lojas/novo',
  path: '/lojas/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojasIdRoute = AdminLojasIdRouteImport.update({
  id: '/lojas/$id',
  path: '/lojas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNovoRoute = AdminBlogNovoRouteImport.update({
  id: '/blog/novo',
  path: '/blog/novo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/conecte-se': typeof ConecteSeRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRouteWithChildren
  '/o-valen': typeof OValenRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/promocoes': typeof PromocoesRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lojas/$slug': typeof LojasSlugRoute
  '/promocoes/$slug': typeof PromocoesSlugRoute
  '/servicos/alimentacao': typeof ServicosAlimentacaoRoute
  '/servicos/clube-do-caminhoneiro': typeof ServicosClubeDoCaminhoneiroRoute
  '/servicos/hotel': typeof ServicosHotelRoute
  '/servicos/posto': typeof ServicosPostoRoute
  '/servicos/truck-center': typeof ServicosTruckCenterRoute
  '/admin/': typeof AdminIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/lojas/$id': typeof AdminLojasIdRoute
  '/admin/lojas/novo': typeof AdminLojasNovoRoute
  '/admin/promocoes/$id': typeof AdminPromocoesIdRoute
  '/admin/promocoes/novo': typeof AdminPromocoesNovoRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/lojas/': typeof AdminLojasIndexRoute
  '/admin/promocoes/': typeof AdminPromocoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/conecte-se': typeof ConecteSeRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRouteWithChildren
  '/o-valen': typeof OValenRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/promocoes': typeof PromocoesRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lojas/$slug': typeof LojasSlugRoute
  '/promocoes/$slug': typeof PromocoesSlugRoute
  '/servicos/alimentacao': typeof ServicosAlimentacaoRoute
  '/servicos/clube-do-caminhoneiro': typeof ServicosClubeDoCaminhoneiroRoute
  '/servicos/hotel': typeof ServicosHotelRoute
  '/servicos/posto': typeof ServicosPostoRoute
  '/servicos/truck-center': typeof ServicosTruckCenterRoute
  '/admin': typeof AdminIndexRoute
  '/servicos': typeof ServicosIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/lojas/$id': typeof AdminLojasIdRoute
  '/admin/lojas/novo': typeof AdminLojasNovoRoute
  '/admin/promocoes/$id': typeof AdminPromocoesIdRoute
  '/admin/promocoes/novo': typeof AdminPromocoesNovoRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/lojas': typeof AdminLojasIndexRoute
  '/admin/promocoes': typeof AdminPromocoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/conecte-se': typeof ConecteSeRoute
  '/contato': typeof ContatoRoute
  '/experiencias': typeof ExperienciasRoute
  '/login': typeof LoginRoute
  '/lojas': typeof LojasRouteWithChildren
  '/o-valen': typeof OValenRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/promocoes': typeof PromocoesRouteWithChildren
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/lojas/$slug': typeof LojasSlugRoute
  '/promocoes/$slug': typeof PromocoesSlugRoute
  '/servicos/alimentacao': typeof ServicosAlimentacaoRoute
  '/servicos/clube-do-caminhoneiro': typeof ServicosClubeDoCaminhoneiroRoute
  '/servicos/hotel': typeof ServicosHotelRoute
  '/servicos/posto': typeof ServicosPostoRoute
  '/servicos/truck-center': typeof ServicosTruckCenterRoute
  '/admin/': typeof AdminIndexRoute
  '/servicos/': typeof ServicosIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/novo': typeof AdminBlogNovoRoute
  '/admin/lojas/$id': typeof AdminLojasIdRoute
  '/admin/lojas/novo': typeof AdminLojasNovoRoute
  '/admin/promocoes/$id': typeof AdminPromocoesIdRoute
  '/admin/promocoes/novo': typeof AdminPromocoesNovoRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/lojas/': typeof AdminLojasIndexRoute
  '/admin/promocoes/': typeof AdminPromocoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/conecte-se'
    | '/contato'
    | '/experiencias'
    | '/login'
    | '/lojas'
    | '/o-valen'
    | '/politica-de-privacidade'
    | '/promocoes'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/lojas/$slug'
    | '/promocoes/$slug'
    | '/servicos/alimentacao'
    | '/servicos/clube-do-caminhoneiro'
    | '/servicos/hotel'
    | '/servicos/posto'
    | '/servicos/truck-center'
    | '/admin/'
    | '/servicos/'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/lojas/$id'
    | '/admin/lojas/novo'
    | '/admin/promocoes/$id'
    | '/admin/promocoes/novo'
    | '/admin/blog/'
    | '/admin/lojas/'
    | '/admin/promocoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/conecte-se'
    | '/contato'
    | '/experiencias'
    | '/login'
    | '/lojas'
    | '/o-valen'
    | '/politica-de-privacidade'
    | '/promocoes'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/lojas/$slug'
    | '/promocoes/$slug'
    | '/servicos/alimentacao'
    | '/servicos/clube-do-caminhoneiro'
    | '/servicos/hotel'
    | '/servicos/posto'
    | '/servicos/truck-center'
    | '/admin'
    | '/servicos'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/lojas/$id'
    | '/admin/lojas/novo'
    | '/admin/promocoes/$id'
    | '/admin/promocoes/novo'
    | '/admin/blog'
    | '/admin/lojas'
    | '/admin/promocoes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/conecte-se'
    | '/contato'
    | '/experiencias'
    | '/login'
    | '/lojas'
    | '/o-valen'
    | '/politica-de-privacidade'
    | '/promocoes'
    | '/termos-de-uso'
    | '/blog/$slug'
    | '/lojas/$slug'
    | '/promocoes/$slug'
    | '/servicos/alimentacao'
    | '/servicos/clube-do-caminhoneiro'
    | '/servicos/hotel'
    | '/servicos/posto'
    | '/servicos/truck-center'
    | '/admin/'
    | '/servicos/'
    | '/admin/blog/$id'
    | '/admin/blog/novo'
    | '/admin/lojas/$id'
    | '/admin/lojas/novo'
    | '/admin/promocoes/$id'
    | '/admin/promocoes/novo'
    | '/admin/blog/'
    | '/admin/lojas/'
    | '/admin/promocoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ConecteSeRoute: typeof ConecteSeRoute
  ContatoRoute: typeof ContatoRoute
  ExperienciasRoute: typeof ExperienciasRoute
  LoginRoute: typeof LoginRoute
  LojasRoute: typeof LojasRouteWithChildren
  OValenRoute: typeof OValenRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PromocoesRoute: typeof PromocoesRouteWithChildren
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ServicosAlimentacaoRoute: typeof ServicosAlimentacaoRoute
  ServicosClubeDoCaminhoneiroRoute: typeof ServicosClubeDoCaminhoneiroRoute
  ServicosHotelRoute: typeof ServicosHotelRoute
  ServicosPostoRoute: typeof ServicosPostoRoute
  ServicosTruckCenterRoute: typeof ServicosTruckCenterRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-valen': {
      id: '/o-valen'
      path: '/o-valen'
      fullPath: '/o-valen'
      preLoaderRoute: typeof OValenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencias': {
      id: '/experiencias'
      path: '/experiencias'
      fullPath: '/experiencias'
      preLoaderRoute: typeof ExperienciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conecte-se': {
      id: '/conecte-se'
      path: '/conecte-se'
      fullPath: '/conecte-se'
      preLoaderRoute: typeof ConecteSeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/servicos/truck-center': {
      id: '/servicos/truck-center'
      path: '/servicos/truck-center'
      fullPath: '/servicos/truck-center'
      preLoaderRoute: typeof ServicosTruckCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/posto': {
      id: '/servicos/posto'
      path: '/servicos/posto'
      fullPath: '/servicos/posto'
      preLoaderRoute: typeof ServicosPostoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/hotel': {
      id: '/servicos/hotel'
      path: '/servicos/hotel'
      fullPath: '/servicos/hotel'
      preLoaderRoute: typeof ServicosHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/clube-do-caminhoneiro': {
      id: '/servicos/clube-do-caminhoneiro'
      path: '/servicos/clube-do-caminhoneiro'
      fullPath: '/servicos/clube-do-caminhoneiro'
      preLoaderRoute: typeof ServicosClubeDoCaminhoneiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/alimentacao': {
      id: '/servicos/alimentacao'
      path: '/servicos/alimentacao'
      fullPath: '/servicos/alimentacao'
      preLoaderRoute: typeof ServicosAlimentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes/$slug': {
      id: '/promocoes/$slug'
      path: '/$slug'
      fullPath: '/promocoes/$slug'
      preLoaderRoute: typeof PromocoesSlugRouteImport
      parentRoute: typeof PromocoesRoute
    }
    '/lojas/$slug': {
      id: '/lojas/$slug'
      path: '/$slug'
      fullPath: '/lojas/$slug'
      preLoaderRoute: typeof LojasSlugRouteImport
      parentRoute: typeof LojasRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/promocoes/': {
      id: '/admin/promocoes/'
      path: '/promocoes'
      fullPath: '/admin/promocoes/'
      preLoaderRoute: typeof AdminPromocoesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/': {
      id: '/admin/lojas/'
      path: '/lojas'
      fullPath: '/admin/lojas/'
      preLoaderRoute: typeof AdminLojasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promocoes/novo': {
      id: '/admin/promocoes/novo'
      path: '/promocoes/novo'
      fullPath: '/admin/promocoes/novo'
      preLoaderRoute: typeof AdminPromocoesNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promocoes/$id': {
      id: '/admin/promocoes/$id'
      path: '/promocoes/$id'
      fullPath: '/admin/promocoes/$id'
      preLoaderRoute: typeof AdminPromocoesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/novo': {
      id: '/admin/lojas/novo'
      path: '/lojas/novo'
      fullPath: '/admin/lojas/novo'
      preLoaderRoute: typeof AdminLojasNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lojas/$id': {
      id: '/admin/lojas/$id'
      path: '/lojas/$id'
      fullPath: '/admin/lojas/$id'
      preLoaderRoute: typeof AdminLojasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/novo': {
      id: '/admin/blog/novo'
      path: '/blog/novo'
      fullPath: '/admin/blog/novo'
      preLoaderRoute: typeof AdminBlogNovoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNovoRoute: typeof AdminBlogNovoRoute
  AdminLojasIdRoute: typeof AdminLojasIdRoute
  AdminLojasNovoRoute: typeof AdminLojasNovoRoute
  AdminPromocoesIdRoute: typeof AdminPromocoesIdRoute
  AdminPromocoesNovoRoute: typeof AdminPromocoesNovoRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminLojasIndexRoute: typeof AdminLojasIndexRoute
  AdminPromocoesIndexRoute: typeof AdminPromocoesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNovoRoute: AdminBlogNovoRoute,
  AdminLojasIdRoute: AdminLojasIdRoute,
  AdminLojasNovoRoute: AdminLojasNovoRoute,
  AdminPromocoesIdRoute: AdminPromocoesIdRoute,
  AdminPromocoesNovoRoute: AdminPromocoesNovoRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminLojasIndexRoute: AdminLojasIndexRoute,
  AdminPromocoesIndexRoute: AdminPromocoesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface LojasRouteChildren {
  LojasSlugRoute: typeof LojasSlugRoute
}

const LojasRouteChildren: LojasRouteChildren = {
  LojasSlugRoute: LojasSlugRoute,
}

const LojasRouteWithChildren = LojasRoute._addFileChildren(LojasRouteChildren)

interface PromocoesRouteChildren {
  PromocoesSlugRoute: typeof PromocoesSlugRoute
}

const PromocoesRouteChildren: PromocoesRouteChildren = {
  PromocoesSlugRoute: PromocoesSlugRoute,
}

const PromocoesRouteWithChildren = PromocoesRoute._addFileChildren(
  PromocoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ConecteSeRoute: ConecteSeRoute,
  ContatoRoute: ContatoRoute,
  ExperienciasRoute: ExperienciasRoute,
  LoginRoute: LoginRoute,
  LojasRoute: LojasRouteWithChildren,
  OValenRoute: OValenRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PromocoesRoute: PromocoesRouteWithChildren,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ServicosAlimentacaoRoute: ServicosAlimentacaoRoute,
  ServicosClubeDoCaminhoneiroRoute: ServicosClubeDoCaminhoneiroRoute,
  ServicosHotelRoute: ServicosHotelRoute,
  ServicosPostoRoute: ServicosPostoRoute,
  ServicosTruckCenterRoute: ServicosTruckCenterRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
